export {
  AUDIO_POOL_SIZE,
  AUDIO_POOL_SIZE_IOS,
  DEFAULT_API_BASE_URL,
  DEFAULT_RETRY_ATTEMPTS,
  DEFAULT_SPEECH_PARAMS,
  DEFAULT_TIMEOUT,
  DEFAULT_VOICE,
  PAUSE_TIMEOUT_MS,
  USER_INTERACTION_EVENTS,
} from './defaults';
